version: '2.2'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    build: .
    restart: always
    depends_on:
      - db
    mem_limit: 500m
    environment:
      - JAVA_OPTS=-Xmx250m -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=1089  -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.0.100
#       - JAVA_OPTS=-Xmx250m
    ports:
      - 1089:1089
    volumes:
      - ./nginx/images/:/mnt/images

  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 4343:4343
    volumes:
      - ./nginx/images/:/var/www/s/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs/:/var/log/nginx/


